name: 📊 Auto Update CSES Progress

on:
  push:
    paths:
      - 'cses/**'
      - '.github/workflows/update-readme.yml'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count files by category
        id: counts
        run: |
          intro=$(find "cses/IntroductoryProblems" -name "*.cpp" 2>/dev/null | wc -l)
          sort=$(find "cses/SortingandSearching" -name "*.cpp" 2>/dev/null | wc -l)
          dp=$(find "cses/DynamicProgramming" -name "*.cpp" 2>/dev/null | wc -l)
          graph=$(find "cses/GraphAlgorithms" -name "*.cpp" 2>/dev/null | wc -l)
          echo "intro=$intro" >> $GITHUB_OUTPUT
          echo "sort=$sort" >> $GITHUB_OUTPUT
          echo "dp=$dp" >> $GITHUB_OUTPUT
          echo "graph=$graph" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -i '/<!--PROGRESS_START-->/,/<!--PROGRESS_END-->/c\
          <!--PROGRESS_START-->\n\
          | Category | Solved |\n\
          |----------|--------|\n\
          | IntroductoryProblems | '${{ steps.counts.outputs.intro }}' |\n\
          | SortingandSearching | '${{ steps.counts.outputs.sort }}' |\n\
          | DynamicProgramming | '${{ steps.counts.outputs.dp }}' |\n\
          | GraphAlgorithms | '${{ steps.counts.outputs.graph }}' |\n\
          <!--PROGRESS_END-->' README.md

      - name: Debug Secret Injection
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "❌ GH_PAT is empty or not configured properly!"
            exit 1
          else
            echo "✅ GH_PAT is injected. Token length: ${#TOKEN}"
          fi

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git config --local --unset-all http.https://github.com/.extraheader
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Tanishq7361/cses.git
          git add README.md
          git commit -m "🔄 auto-update README with progress" || echo "No changes to commit"
          git push origin HEAD:main
