name: 📊 Auto Update CSES Progress

on:
  push:
    paths:
      - 'cses/**'
      - '.github/workflows/update-readme.yml'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count files by category
        id: counts
        run: |
          intro=$(find "cses/Introductory Problems" -name "*.cpp" | wc -l || echo 0)
          sort=$(find "cses/Sorting and Searching" -name "*.cpp" | wc -l || echo 0)
          dp=$(find "cses/Dynamic Programming" -name "*.cpp" | wc -l || echo 0)
          graph=$(find "cses/Graph Algorithms" -name "*.cpp" | wc -l || echo 0)
          echo "intro=$intro" >> $GITHUB_OUTPUT
          echo "sort=$sort" >> $GITHUB_OUTPUT
          echo "dp=$dp" >> $GITHUB_OUTPUT
          echo "graph=$graph" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -i '/<!--PROGRESS_START-->/,/<!--PROGRESS_END-->/c\
          <!--PROGRESS_START-->\n\
          | Category | Solved |\n\
          |----------|--------|\n\
          | Introductory Problems | '"${{ steps.counts.outputs.intro }}"' |\n\
          | Sorting and Searching | '"${{ steps.counts.outputs.sort }}"' |\n\
          | Dynamic Programming | '"${{ steps.counts.outputs.dp }}"' |\n\
          | Graph Algorithms | '"${{ steps.counts.outputs.graph }}"' |\n\
          <!--PROGRESS_END-->' README.md

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "🔄 auto-update README with progress" || echo "No changes to commit"
          git push
