name: 📊 Auto Update CSES Progress

on:
  push:
    paths:
      - 'cses/**'
      - '.github/workflows/update-readme.yml'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count files by category
        id: counts
        run: |
          intro=$(find "Introductory Problems" -name "*.cpp" 2>/dev/null | wc -l)
          sort=$(find "Sorting and Searching" -name "*.cpp" 2>/dev/null | wc -l)
          dp=$(find "Dynamic Programming" -name "*.cpp" 2>/dev/null | wc -l)
          graph=$(find "Graph Algorithms" -name "*.cpp" 2>/dev/null | wc -l)
          inter=$(find "Interactive Problems" -name "*.cpp" 2>/dev/null | wc -l)
          math=$(find "Mathematics" -name "*.cpp" 2>/dev/null | wc -l)
          range=$(find "Range Queries" -name "*.cpp" 2>/dev/null | wc -l)
          string=$(find "String Algorithm" -name "*.cpp" 2>/dev/null | wc -l)
          bit=$(find "Bitwise Operation" -name "*.cpp" 2>/dev/null | wc -l)
          echo "intro=$intro" >> $GITHUB_OUTPUT
          echo "sort=$sort" >> $GITHUB_OUTPUT
          echo "dp=$dp" >> $GITHUB_OUTPUT
          echo "graph=$graph" >> $GITHUB_OUTPUT
          echo "inter=$inter" >> $GITHUB_OUTPUT
          echo "math=$math" >> $GITHUB_OUTPUT
          echo "range=$range" >> $GITHUB_OUTPUT
          echo "string=$string" >> $GITHUB_OUTPUT
          echo "bit=$bit" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -i '/<!--PROGRESS_START-->/,/<!--PROGRESS_END-->/c\
          <!--PROGRESS_START-->\n\
          | Category | Solved |\n\
          |----------|--------|\n\
          | Introductory Problems | '${{ steps.counts.outputs.intro }}' |\n\
          | Sorting and Searching | '${{ steps.counts.outputs.sort }}' |\n\
          | Dynamic Programming | '${{ steps.counts.outputs.dp }}' |\n\
          | Graph Algorithms | '${{ steps.counts.outputs.graph }}' |\n\
          | Interactive Problems | '${{ steps.counts.outputs.inter }}' |\n\
          | Mathematics | '${{ steps.counts.outputs.math }}' |\n\
          | Range Queries | '${{ steps.counts.outputs.range }}' |\n\
          | String Algorithm | '${{ steps.counts.outputs.string }}' |\n\
          | Bitwise Operation | '${{ steps.counts.outputs.bit }}' |\n\
          <!--PROGRESS_END-->' README.md

      - name: Debug Secret Injection
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "❌ GH_PAT is empty or not configured properly!"
            exit 1
          else
            echo "✅ GH_PAT is injected. Token length: ${#TOKEN}"
          fi

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git config --local --unset-all http.https://github.com/.extraheader
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Tanishq7361/cses.git
          git add README.md
          git commit -m "🔄 auto-update README with progress" || echo "No changes to commit"
          git push origin HEAD:main
